### ISSUE TITLE
What obstacles did you encounter when using nix on macOS?

### ISSUE THREAD

**Issue by hgl** [mitchellh/nixos-config#30]
@mitchellh, first I want to thank you for sharing your nix config, that's what got me started in nix.

I remember read it somewhere that you decided to use nixos in a VM because nix on macOS caused enough trouble or something like that.

I'm a happy nixos-in-VM user, but couldn't help but wondering what a nix-on-macOS life would be like. So I'd be interested to hear what obstacles you encountered, if you still remember.

**Comment by mitchellh** [comment]
I didn't have "trouble" on macOS. I got Nix on Darwin working decently well. 

My main reason for using NixOS was because I wanted my full dev env system under Nix and Nix-on-Darwin is of course a mix of Nix and non-Nix system management. Ultimately, I've been considering re-adopting Nix on Darwin for _some_ things (while continuing to work full time in my VM).

**Comment by hgl** [comment]
> I didn't have "trouble" on macOS

Hmm, I was pretty sure it was the other way around. Someone must have inceptioned me. I need to check if my Hashicorp Vault is still safe.

> I've been considering re-adopting Nix on Darwin for some things

That sounds like an interesting approach. I'll try it too. Thanks.
